Controllers/AddrController.cs
using HealthApplication.Data;
using HealthApplication.Models;
using Microsoft.AspNetCore.Mvc;

namespace HealthApplication.Controllers
{
    public class AddrController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AddrController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<Addr> objCatlist = _context.Addrs;
            return View(objCatlist);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Addr addrobj)
        {
            if (ModelState.IsValid)
            {
                var cdate=DateTime.Now;
                addrobj.RecordCreatedOn = cdate;

                _context.Addrs.Add(addrobj);
                _context.SaveChanges();
                TempData["ResultOk"] = "Record Added Successfully !";
                //return RedirectToAction("Index");
                return RedirectToAction("Identity/Account", "Login");
            }

            return View(addrobj);
        }

    }
}

Views/Addr/Create.cshtml
@model Addr


<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Add Address</h2>
    </div>

    <form method="post">
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Building">Building Name</label>
                <input type="text" class="form-control mb-3" asp-for="Building" placeholder="Enter Building Name">
                <span asp-validation-for="Building" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Level">Level</label>
                <input type="text" class="form-control mb-3" asp-for="Level" placeholder="Enter DesiLevelgnation">
                <span asp-validation-for="Level" class=" alert-danger"></span>
            </div>
        </div>

          <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Room">Room</label>
                <input type="text" class="form-control mb-3" asp-for="Room" placeholder="Enter Room Number">
                <span asp-validation-for="Room" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Carpark">Carpark</label>
                <input type="text" class="form-control mb-3" asp-for="Carpark" placeholder="Enter Carpark">
                <span asp-validation-for="Carpark" class=" alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Lobby">Lobby</label>
                <input type="text" class="form-control mb-3" asp-for="Lobby" placeholder="Enter Lobby">
                <span asp-validation-for="Lobby" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Pantry">Pantry</label>
                 <input type="text" class="form-control mb-3" asp-for="Pantry" placeholder="Enter Pantry">
                <span asp-validation-for="Pantry" class=" alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Type">Type</label>
                <input type="text" class="form-control mb-3" asp-for="Type" placeholder="Enter Type">
                <span asp-validation-for="Type" class=" alert-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Save</button>
        <a asp-controller="Addr" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To List</a>
    </form>

</div>


@*//for front end validations*@

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

Views/Addr/Index.cshtml
@model IEnumerable<Addr>

    @{
    ViewData["Title"] = "Index";
}

@if (TempData["ResultOk"] != null)
{
    <h1 class="alert-success">@TempData["ResultOk"]</h1>
}

<div class="container shadow p-5">

    <h1 class="text-center mb-3">CRUD Operations Using .NET Core 6 & Microsoft.EntityFrameworkCore </h1>

    <div class="col mb-3">
        <a asp-controller="Addr" asp-action="Create" class="btn btn-lg btn-primary"><i class="bi bi-file-plus-fill"></i>Add Address</a>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col">Building Name</th>
                <th scope="col">Level</th>
                <th scope="col">Room</th>
                <th scope="col">Carpark</th>
                <th scope="col">Lobby</th>
                <th scope="col">Pantry</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td width="15%">
                        @item.Building
                    </td>
                    <td width="15%">
                        @item.Level
                    </td>
                    <td width="15%">
                        @item.Room
                    </td>
                    <td width="15%">
                        @item.Carpark
                    </td>
                    <td width="15%">
                        @item.Lobby
                    </td>
                    <td width="15%">
                        @item.Pantry
                    </td>
                    <td width="10%">
                        @item.Type
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>